const countries = [
  { code: "us", region: "United States" },
  { code: "uk", region: "United Kingdom" },
  { code: "ca", region: "Canada" },
  { code: "ru", region: "Russia" },
  { code: "de", region: "Germany" },
  { code: "fr", region: "France" },
  { code: "es", region: "Spain" },
  { code: "it", region: "Italy" },
  { code: "br", region: "Brazil" },
  { code: "au", region: "Australia" },
  { code: "ar", region: "Argentina" },
  { code: "be", region: "Belgium" },
  { code: "ch", region: "Switzerland" },
  { code: "dk", region: "Denmark" },
  { code: "fi", region: "Finland" },
  { code: "hk", region: "Hong Kong" },
  { code: "ie", region: "Ireland" },
  { code: "il", region: "Israel" },
  { code: "mx", region: "Mexico" },
  { code: "nl", region: "Netherlands" },
  { code: "no", region: "Norway" },
  { code: "pl", region: "Poland" },
  { code: "se", region: "Sweden" },
  { code: "sg", region: "Singapore" },
  { code: "tr", region: "Turkey" },
  { code: "jp", region: "Japan" },
  { code: "in", region: "India" },
  { code: "hu", region: "Hungary" },
  { code: "af", region: "Afghanistan" },
  { code: "al", region: "Albania" },
  { code: "dz", region: "Algeria" },
  { code: "ao", region: "Angola" },
  { code: "am", region: "Armenia" },
  { code: "at", region: "Austria" },
  { code: "az", region: "Azerbaijan" },
  { code: "bh", region: "Bahrain" },
  { code: "bd", region: "Bangladesh" },
  { code: "by", region: "Belarus" },
  { code: "bz", region: "Belize" },
  { code: "bo", region: "Bolivia" },
  { code: "ba", region: "Bosnia and Herzegovina" },
  { code: "bw", region: "Botswana" },
  { code: "bn", region: "Brunei" },
  { code: "bg", region: "Bulgaria" },
  { code: "cv", region: "Cabo Verde" },
  { code: "kh", region: "Cambodia" },
  { code: "cm", region: "Cameroon" },
  { code: "cl", region: "Chile" },
  { code: "co", region: "Colombia" },
  { code: "cr", region: "Costa Rica" },
  { code: "hr", region: "Croatia" },
  { code: "cy", region: "Cyprus" },
  { code: "cz", region: "Czech Republic   " },
  { code: "cd", region: "Congo" },
  { code: "do", region: "Dominican Republic" },
  { code: "ec", region: "Ecuador" },
  { code: "eg", region: "Egypt" },
  { code: "sv", region: "El Salvador" },
  { code: "ee", region: "Estonia" },
  { code: "et", region: "Ethiopia" },
  { code: "ge", region: "Georgia" },
  { code: "gh", region: "Ghana" },
  { code: "gr", region: "Greece" },
  { code: "gt", region: "Guatemala" },
  { code: "gy", region: "Guyana" },
  { code: "ht", region: "Haiti" },
  { code: "hn", region: "Honduras" },
  { code: "is", region: "Iceland" },
  { code: "id", region: "Indonesia" },
  { code: "jm", region: "Jamaica" },
  { code: "jo", region: "Jordan" },
  { code: "kz", region: "Kazakhstan" },
  { code: "kw", region: "Kuwait" },
  { code: "lv", region: "Latvia" },
  { code: "lb", region: "Lebanon" },
  { code: "lt", region: "Lithuania" },
  { code: "lu", region: "Luxembourg" },
  { code: "mg", region: "Madagascar" },
  { code: "my", region: "Malaysia" },
  { code: "mt", region: "Malta" },
  { code: "mu", region: "Mauritius" },
  { code: "md", region: "Moldova" },
  { code: "mn", region: "Mongolia" },
  { code: "me", region: "Montenegro" },
  { code: "ma", region: "Morocco" },
  { code: "mz", region: "Mozambique" },
  { code: "na", region: "Namibia" },
  { code: "np", region: "Nepal" },
  { code: "nz", region: "New Zealand" },
  { code: "ni", region: "Nicaragua" },
  { code: "ng", region: "Nigeria" },
  { code: "om", region: "Oman" },
  { code: "py", region: "Paraguay" },
  { code: "pe", region: "Peru" },
  { code: "ph", region: "Philippines" },
  { code: "pt", region: "Portugal" },
  { code: "ro", region: "Romania" },
  { code: "sa", region: "Saudi Arabia   " },
  { code: "sn", region: "Senegal" },
  { code: "rs", region: "Serbia" },
  { code: "sk", region: "Slovakia" },
  { code: "si", region: "Slovenia" },
  { code: "za", region: "South Africa   " },
  { code: "kr", region: "South Korea" },
  { code: "lk", region: "Sri Lanka" },
  { code: "th", region: "Thailand" },
  { code: "bs", region: "Bahamas" },
  { code: "tt", region: "Trinidad and Tobago" },
  { code: "tn", region: "Tunisia" },
  { code: "ua", region: "Ukraine" },
  { code: "ae", region: "United Arab Emirates" },
  { code: "uy", region: "Uruguay" },
  { code: "ve", region: "Venezuela" },
  { code: "vn", region: "Vietnam" },
  { code: "zm", region: "Zambia" },
  { code: "zw", region: "Zimbabwe" },
  { code: "ly", region: "Libya     " },
  { code: "pk", region: "Pakistan" },
];

export default countries;
